labels:
  role: awsbuilder
  platform: linux/aarch64

matrix:
  GCC:
    - 11
    - 8
    - 6

steps:
  - name: build-ppc-amigaos-gcc${GCC}-base
    image: plugins/docker
    settings:
      repo: walkero/amigagccondocker
      # registry: https://index.docker.io/v1/
      dockerfile: ppc-amigaos/Dockerfile
      context: ppc-amigaos
      compress: true
      purge: true
      # dry-run: true
      cache_from:
        - walkero/amigagccondocker:os4-gcc${GCC}-base-arm64
      build_args:
        - GCC_VER=11
      tags:
        - os4-gcc${GCC}-base-arm64
        - os4-gcc${GCC}-base-${CI_COMMIT_TAG}-arm64
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD

when:
  - branch: main
    event: [push, tag]

depends_on:
  - aws-poweron