labels:
  role: awsbuilder

steps:
  - name: build-os4-gcc11-base
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/aarch64
      repo: walkero/amigagccondocker
      # registry: https://index.docker.io/v1/
      dockerfile: os4/Dockerfile
      context: os4
      compress: true
      purge: true
      build_args:
        - OS: os4
        - GCC_VER: 11
      tags:
        - os4-gcc11-base-testing
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD

when:
  - branch: main
    event: [push, tag]

depends_on:
  - aws-poweron